# Generated by Django 4.0.4 on 2022-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0004_alter_album_offer_of_the_week_alter_mediatype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default='Описание появится позже', verbose_name='Биография группы'),
        ),
    ]
